apiVersion: v1
kind: Service
metadata:
  name: htmllatestpage-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: htmllatestpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
